version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - gosec
  settings:
    gofmt:
      simplify: true

linters:
  default: standard
  enable:
    - revive
    - misspell
    - gocritic

  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: if-return
        - name: increment-decrement
        - name: range

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Close`"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
